// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBzYKNoHdBSXN77HVTTNuEFZ0U4eRFS8M',
    appId: '1:484932274756:web:3511396c4c4026fc5a8a11',
    messagingSenderId: '484932274756',
    projectId: 'wact-95d5b',
    authDomain: 'wact-95d5b.firebaseapp.com',
    storageBucket: 'wact-95d5b.appspot.com',
    measurementId: 'G-RGL18PF6F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB803Mu_DS3gRpF-qRomHVubjT8nVy_BTk',
    appId: '1:484932274756:android:378d1942b8e714885a8a11',
    messagingSenderId: '484932274756',
    projectId: 'wact-95d5b',
    storageBucket: 'wact-95d5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQY4bTVLjjks5rx-DMqnpzpse9dCRsGcs',
    appId: '1:484932274756:ios:6a994f4fad3d23e75a8a11',
    messagingSenderId: '484932274756',
    projectId: 'wact-95d5b',
    storageBucket: 'wact-95d5b.appspot.com',
    iosBundleId: 'com.one.wact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQY4bTVLjjks5rx-DMqnpzpse9dCRsGcs',
    appId: '1:484932274756:ios:367906a81e1f17a75a8a11',
    messagingSenderId: '484932274756',
    projectId: 'wact-95d5b',
    storageBucket: 'wact-95d5b.appspot.com',
    iosBundleId: 'com.example.wact.RunnerTests',
  );
}
